version: "3.3"
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=prod
    volumes:
      - ./gitignore/postgresql:/var/lib/postgresql/data
    ports:
      - 5430:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8079:8080
