"""empty message

Revision ID: 066f516698ff
Revises: 4fbca63dad38
Create Date: 2020-04-08 15:59:40.073173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066f516698ff'
down_revision = '4fbca63dad38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('personal_email', sa.VARCHAR(length=20), nullable=True))
    op.create_unique_constraint(None, 'recruits', ['personal_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruits', type_='unique')
    op.drop_column('recruits', 'personal_email')
    # ### end Alembic commands ###
